apiVersion: v2
name: openebs-stack
version: 0.1.3
description: Full stack including PostgreSQL, Redis, Kafka, Quickwit, Debezium CDC
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: kafka
    version: 26.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: rabbitmq
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql-ha
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql-ha.enabled
