FROM confluentinc/cp-kafka-connect:7.6.0

USER root

# 安装 Debezium PostgreSQL 插件
RUN mkdir -p /usr/share/java/kafka/plugins/debezium && \
    curl -L https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.6.0.Final/debezium-connector-postgres-2.6.0.Final-plugin.tar.gz \
    | tar -xz -C /usr/share/java/kafka/plugins/debezium

ENV CONNECT_PLUGIN_PATH="/usr/share/java/kafka/plugins"

USER appuser