postgresql:
  image:
    registry: sxwl-registry.cn-beijing.cr.aliyuncs.com
    repository: sxwl-ai/postgresql-vector
    tag: "16"
  repmgrUsername: repmgr
  repmgrPassword: repmgrpassword
  repmgrDatabase: repmgr
  password: yourpassword
  username: postgres
  database: yourdb

  extendedConf:
    wal_level: logical
    max_replication_slots: 10
    max_wal_senders: 10

  persistence:
    enabled: true
    storageClass: openebs-cstor
    size: 10Gi

  # 高可用集群配置
  architecture: replication
  replicaCount: 2  # 2个从节点 + 1个主节点，总共3个实例
  
  # 高可用自动故障转移配置
  repmgrAutoFailover: true
  repmgrConnectTimeout: 5
  repmgrReconnectAttempts: 3
  repmgrReconnectInterval: 5

  primary:
    persistence:
      storageClass: openebs-cstor
      size: 10Gi
      
  readReplicas:
    persistence:
      storageClass: openebs-cstor
      size: 10Gi
    replicaCount: 2  # 明确设置读取副本数量为2
      
  pgpool:
    enabled: true  # 确保pgpool启用
    replicaCount: 2  # pgpool副本数量提升为2个实现高可用
    persistence:
      enabled: false
    adminUsername: admin
    adminPassword: adminpassword
    configuration: |
      failover_on_backend_error = on
      failover_command = '/scripts/pgpool/failover.sh %d %h %p %D %m %H %M %P %r %R'
      backend_flag0 = 'ALLOW_TO_FAILOVER'
      backend_flag1 = 'ALLOW_TO_FAILOVER'
      backend_flag2 = 'ALLOW_TO_FAILOVER'

  volumePermissions:
    enabled: true

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

redis:
  architecture: replication
  image:
    tag: 6.2.14-debian-11-r8
  auth:
    enabled: true
    password: "redis-password" # 添加认证
  sentinel:
    enabled: true
    replicas: 3
    downAfterMilliseconds: 5000
    failoverTimeout: 10000
    parallelSyncs: 1
  persistence:
    enabled: true
    storageClass: openebs-cstor
    size: 5Gi
  replica:
    replicaCount: 3
    persistence:
      storageClass: openebs-cstor
      size: 5Gi

rabbitmq:
  image:
    tag: 3.13.1-debian-12-r1
  replicaCount: 3
  clustering:
    enabled: true
  persistence:
    storageClass: openebs-cstor
    size: 5Gi
  extraConfiguration: |
    loopback_users.guest = false
    default_permissions.configure = .*
    default_permissions.write = .*
    default_permissions.read = .*
    cluster_partition_handling = autoheal
    queue_master_locator = min-masters
    default_vhost = /

kafka:
  kraft:
    enabled: true
    combinedMode: true
  controller:
    replicaCount: 3  # 确保有3个controller节点
    persistence:
      enabled: true
      storageClass: openebs-cstor
      size: 20Gi
  broker:
    replicaCount: 0  # 在combinedMode为true时设为0，避免创建额外的broker pod
  persistence:
    enabled: true
    storageClass: openebs-cstor
    size: 20Gi
  auth:
    enabled: true
    clientProtocol: sasl
    interBrokerProtocol: sasl
  resources:
    requests:
      memory: 4Gi
      cpu: 1
    limits:
      memory: 8Gi
      cpu: 2
  heapOpts: "-Xms2G -Xmx4G"

kafkaConnect:
  enabled: true
  image: sxwl-registry.cn-beijing.cr.aliyuncs.com/sxwl-ai/kafka-connect-debezium:latest
  bootstrapServers: openebs-stack-kafka:9092
  replicaCount: 3
  extraEnvVars:
    - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
      value: "3"
    - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
      value: "3"
    - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
      value: "3"
    - name: CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
      value: "true"
    - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
      value: "true"
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

quickwit:
  enabled: true
  replicaCount: 3
  pvcSize: 20Gi
  storagePath: /quickwit/indexes
  storageClass: openebs-cstor
  image: quickwit/quickwit:0.8.1
  extraEnvVars:
    - name: QW_NODE_ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: QW_METASTORE_URI
      value: postgres://postgres:yourpassword@openebs-stack-postgresql-primary:5432/yourdb
    - name: QW_LISTEN_ADDRESS
      value: 0.0.0.0
    - name: QW_REST_LISTEN_PORT
      value: "7280"
    - name: QW_GOSSIP_LISTEN_PORT
      value: "7280"
    - name: QW_CLUSTER_ID
      value: quickwit-cluster
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m