
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  labels:
    app: kafka-connect
    app.kubernetes.io/instance: openebs-stack
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app: kafka-connect
  ports:
    - name: rest
      port: 8083
      targetPort: 8083
