apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-vector-setup
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: pg-client
        image: postgres:16
        command:
        - /bin/bash
        - -c
        - |
          PGPASSWORD={{ .Values.postgresql.auth.password }} psql -h {{ .Release.Name }}-postgresql -U {{ .Values.postgresql.auth.username }} -d {{ .Values.postgresql.auth.database }} -c "CREATE EXTENSION IF NOT EXISTS vector;"
      restartPolicy: OnFailure
  backoffLimit: 5