apiVersion: apps/v1
kind: Deployment
metadata:
  name: openebs-stack-quickwit
  labels:
    app.kubernetes.io/name: quickwit
    app.kubernetes.io/part-of: openebs-stack
spec:
  replicas: {{ .Values.quickwit.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: quickwit
      app.kubernetes.io/part-of: openebs-stack
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quickwit
        app.kubernetes.io/part-of: openebs-stack
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.34
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for Kafka to be ready..."
              sleep 10
      containers:
        - name: quickwit
          image: {{ .Values.quickwit.image | default "quickwit/quickwit:0.8.1" }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              # 从Secret获取密码
              echo "从Secret获取Kafka密码..."
              PASSWORD=$(cat /secrets/client-passwords)
              if [ -z "$PASSWORD" ]; then
                echo "错误: 无法获取Kafka密码!"
                exit 1
              fi
              
              # 设置环境变量
              export QW_KAFKA__SASL_USERNAME="user1"
              export QW_KAFKA__SASL_PASSWORD="$PASSWORD"
              
              echo "凭据设置完成，启动Quickwit..."
              exec quickwit run
          ports:
            - containerPort: 7280
          volumeMounts:
            - name: quickwit-data
              mountPath: {{ .Values.quickwit.storagePath }}
            - name: kafka-secrets
              mountPath: /secrets
          env:
            - name: QW_KAFKA__BOOTSTRAP_SERVERS
              value: openebs-stack-kafka:9092
            - name: QW_KAFKA__SECURITY_PROTOCOL
              value: SASL_PLAINTEXT
            - name: QW_KAFKA__SASL_MECHANISM
              value: PLAIN
{{- with .Values.quickwit.extraEnvVars }}
{{ toYaml . | indent 12 }}
{{- end }}
      volumes:
        - name: quickwit-data
          persistentVolumeClaim:
            claimName: quickwit-pvc
        - name: kafka-secrets
          secret:
            secretName: openebs-stack-kafka-user-passwords
            optional: true

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quickwit-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.quickwit.pvcSize }}
  storageClassName: {{ .Values.storageClass }}