apiVersion: v1
kind: Service
metadata:
  name: openebs-stack-quickwit
  labels:
    app: quickwit
    app.kubernetes.io/name: quickwit
    app.kubernetes.io/part-of: openebs-stack
spec:
  ports:
    - port: 7280
      targetPort: 7280
      name: http
  selector:
    app: quickwit
  type: ClusterIP