apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openebs-stack-quickwit
  labels:
    app: quickwit
    app.kubernetes.io/instance: openebs-stack
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.quickwit.replicaCount }}
  serviceName: "openebs-stack-quickwit-headless"  # 为StatefulSet定义Headless Service
  selector:
    matchLabels:
      app: quickwit
  template:
    metadata:
      labels:
        app: quickwit
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.34
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for Kafka to be ready..."
              sleep 10
      containers:
        - name: quickwit
          image: {{ .Values.quickwit.image | default "quickwit/quickwit:0.8.1" }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              # 从Secret获取密码
              echo "从Secret获取Kafka密码..."
              PASSWORD=$(cat /secrets/client-passwords)
              if [ -z "$PASSWORD" ]; then
                echo "错误: 无法获取Kafka密码!"
                exit 1
              fi
              
              # 设置环境变量
              export QW_KAFKA__SASL_USERNAME="user1"
              export QW_KAFKA__SASL_PASSWORD="$PASSWORD"
              
              echo "凭据设置完成，启动Quickwit..."
              exec quickwit run
          ports:
            - containerPort: 7280
              name: http
          volumeMounts:
            - name: quickwit-data
              mountPath: {{ .Values.quickwit.storagePath }}
            - name: kafka-secrets
              mountPath: /secrets
            - name: minio-creds
              mountPath: /minio-secrets
          env:
            - name: QW_KAFKA__BOOTSTRAP_SERVERS
              value: openebs-stack-kafka:9092
            - name: QW_KAFKA__SECURITY_PROTOCOL
              value: SASL_PLAINTEXT
            - name: QW_KAFKA__SASL_MECHANISM
              value: PLAIN
{{- with .Values.quickwit.extraEnvVars }}
{{ toYaml . | indent 12 }}
{{- end }}
      volumes:
        - name: kafka-secrets
          secret:
            secretName: openebs-stack-kafka-user-passwords
            optional: true
        - name: minio-creds
          secret:
            secretName: minio-credentials
  # 使用volumeClaimTemplates替代单一PVC
  volumeClaimTemplates:
    - metadata:
        name: quickwit-data
        labels:
          app.kubernetes.io/instance: openebs-stack
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.quickwit.pvcSize }}
        storageClassName: {{ .Values.quickwit.storageClass | default "openebs-cstor" }}

---

# 为StatefulSet创建一个Headless Service
apiVersion: v1
kind: Service
metadata:
  name: openebs-stack-quickwit-headless
  labels:
    app: quickwit
    app.kubernetes.io/instance: openebs-stack
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None  # Headless服务的关键配置
  selector:
    app: quickwit
  ports:
    - port: 7280
      name: http 