apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-role-labeler
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: openebs-stack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-role-labeler
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: openebs-stack
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-role-labeler-binding
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: openebs-stack
subjects:
  - kind: ServiceAccount
    name: postgres-role-labeler
    namespace: default
roleRef:
  kind: Role
  name: postgres-role-labeler
  apiGroup: rbac.authorization.k8s.io